### ISSUE TITLE
请问数据集格式和样例是什么？

### ISSUE THREAD

**Issue by Alexkerl** [ShaoboZhang/Workshop#1]

**Comment by ShaoboZhang** [comment]
原始数据是json格式，我这里用的是我处理了下生成的txt文件。

**Comment by ShaoboZhang** [comment]
原始数据是json格式，我处理了一下保存成txt（这一步我没写进来）。格式的话每行文本前面是原文，后面是摘要，用分隔符隔开。你如果需要数据可以发我邮件我发给你。

**Comment by Alexkerl** [comment]
> 原始数据是json格式，我处理了一下保存成txt（这一步我没写进来）。格式的话每行文本前面是原文，后面是摘要，用分隔符隔开。你如果需要数据可以发我邮件我发给你。

好的，如果数据方便公开发到program_design@163.com邮箱或百度网盘都行，谢谢

**Comment by ojbkaaaa** [comment]
470345435@qq.com可以也发我一份吗？谢谢

**Comment by LeafCloud** [comment]
1905368291@qq.com能发我一份吗，谢谢

**Comment by ShaoboZhang** [comment]
> [470345435@qq.com](mailto:470345435@qq.com)可以也发我一份吗？谢谢

> [1905368291@qq.com](mailto:1905368291@qq.com)能发我一份吗，谢谢

已发，请查收

**Comment by wangcuilin** [comment]
你好，请问您方便把.pt文件发给我吗？

**Comment by ShaoboZhang** [comment]
你好，抱歉，我后来没把跑出来的结果存到网盘里。你是遇到什么问题了吗？模型跑出来的效果不好？

**Comment by ShaoboZhang** [comment]
这个模型我实现的也比较粗糙，只是为了简历上有点东西，395492749，这个是我的qq，你要是比较急，可以加我讨论一下。

**Comment by yuulin** [comment]
yuulin@163.com数据集可以也发我一份吗？谢谢

**Comment by ShaoboZhang** [comment]
> [yuulin@163.com](mailto:yuulin@163.com)数据集可以也发我一份吗？谢谢

已发送，请查收

**Comment by Cooperhgp** [comment]
244269108@qq.com 数据集可以也发我一份吗？谢谢

**Comment by ShaoboZhang** [comment]
> [244269108@qq.com](mailto:244269108@qq.com) 数据集可以也发我一份吗？谢谢

已发送，请查收

**Comment by guangh01** [comment]
vang_guan@163.com  数据集可以也发我一份吗？谢谢

**Comment by ShaoboZhang** [comment]
> [vang_guan@163.com](mailto:vang_guan@163.com) 数据集可以也发我一份吗？谢谢

已发送，请查收

**Comment by fenfaqingnian** [comment]
2896796692@qq.com  数据集可以分享一下吗，谢谢

**Comment by qingpu1996** [comment]
你好，方便发我一份数据集吗，qdino1996@gmail.com

**Comment by fenfaqingnian** [comment]
https://pan.baidu.com/s/1QAqIx1Zv7PYYNY0kBMp98w&nbsp;提取码: iol2
请查收





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ShaoboZhang/Workshop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月17日(星期五) 下午4:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ShaoboZhang/Workshop] 请问数据集格式和样例是什么？ (#1)





 
***@***.***
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ShaoboZhang** [comment]
> 你好，方便发我一份数据集吗，[qdino1996@gmail.com](mailto:qdino1996@gmail.com)

已发送，请尽快查收

**Comment by sansiny** [comment]
> 你好，还方便发我一份数据集吗  yonghengzhilu@126.com 谢谢！

**Comment by linshaoxin-maker** [comment]
你好，还方便发我一份数据集吗 [983586218@qq.com](mailto:983586218@qq.com) 谢谢！

**Comment by ShaoboZhang** [comment]
> > 你好，还方便发我一份数据集吗  [yonghengzhilu@126.com](mailto:yonghengzhilu@126.com) 谢谢！

已发送，请尽快查收

**Comment by ShaoboZhang** [comment]
> 你好，还方便发我一份数据集吗 [983586218@qq.com](mailto:983586218@qq.com) 谢谢！

已发送，请尽快查收

**Comment by doncat99** [comment]
你好，还方便发我一份数据集吗 [45198852@qq.com](mailto:45198852@qq.com) 谢谢！

**Comment by ShaoboZhang** [comment]
> 你好，还方便发我一份数据集吗 [45198852@qq.com](mailto:45198852@qq.com) 谢谢！

已发送，请查收

**Comment by justfuwei** [comment]
你好，方便发一份数据给我吗， 1929881656@qq.com 谢谢

**Comment by PinzhengWang322** [comment]
你好，还方便发我一份数据集吗， [2876048220@qq.com](mailto:2876048220@qq.com) 谢谢！

**Comment by nlp-learner** [comment]
你好，方便发我一份数据集吗，874790716@qq.com,谢谢！

**Comment by ShaoboZhang** [comment]
> 你好，方便发一份数据给我吗， [1929881656@qq.com](mailto:1929881656@qq.com) 谢谢

已发送，请查收

**Comment by ShaoboZhang** [comment]
> 874790716@qq.com

已发送，请查收

**Comment by ShaoboZhang** [comment]
> 你好，方便发我一份数据集吗，[874790716@qq.com](mailto:874790716@qq.com),谢谢！

已发送，请查收

**Comment by ghostxu97** [comment]
你好，数据集可以给我发一份吗，1909148276@qq.com 谢谢！

**Comment by Beakboomboom** [comment]
你好，方便发一份数据给我吗，493932879@qq.com 非常感谢！

**Comment by ShaoboZhang** [comment]
> [493932879@qq.com](mailto:493932879@qq.com)

已发送，请查收

**Comment by ShaoboZhang** [comment]
> 你好，方便发一份数据给我吗，[493932879@qq.com](mailto:493932879@qq.com) 非常感谢！

已发送，请查收

**Comment by 980202006** [comment]
你好，方便发一份数据给我吗，fujindemi@gmail.com @ShaoboZhang 非常感谢！

**Comment by czydxx** [comment]
你好，方便发一份数据给我吗，497336236@qq.com  非常感谢！

**Comment by HDRBgg** [comment]
你好，方便发一份数据给我吗，1051673253@qq.com非常感谢！

**Comment by ShaoboZhang** [comment]
> 你好，方便发一份数据给我吗，[fujindemi@gmail.com](mailto:fujindemi@gmail.com) @ShaoboZhang 非常感谢！

已发送，请查收

**Comment by ShaoboZhang** [comment]
> 已发送，请查收



> 你好，方便发一份数据给我吗，[497336236@qq.com](mailto:497336236@qq.com) 非常感谢！

已发送，请查收

**Comment by ShaoboZhang** [comment]
> 你好，方便发一份数据给我吗，[1051673253@qq.com](mailto:1051673253@qq.com)非常感谢！

已发送，请查收

**Comment by kennyLSN** [comment]
你好，方便发一份数据给我吗，13127530228@163.com 谢谢！

**Comment by kennyLSN** [comment]
你好，方便发我一份数据吗，1104890726@qq.com 感谢

**Comment by ShaoboZhang** [comment]
> 1104890726@qq.com

已发送，请查收

**Comment by ShaoboZhang** [comment]
> 你好，方便发我一份数据吗，[1104890726@qq.com](mailto:1104890726@qq.com) 感谢

已发送，请查收

**Comment by liushuchun** [comment]
@ShaoboZhang 多谢作者。

**Comment by ShaoboZhang** [comment]
> 249797135@qq.com

发你了，请查收

**Comment by liushuchun** [comment]
多谢作者了。
